import pizza from "./src/assets/pizza.avif";
import burger from "./src/assets/burger.avif";
import pasta from "./src/assets/pasta.avif";
import soup from "./src/assets/soup.avif";
import dosa from "./src/assets/dosa.avif";
import paneer from "./src/assets/paneer.avif";
import biryani from "./src/assets/biryani.avif";
import pancakes from "./src/assets/pancake.avif";
import fries from "./src/assets/fries.avif";
import icecream from "./src/assets/icecream.avif";
import cake from "./src/assets/cake.avif";
import noodles from "./src/assets/noodles.avif";
import rice from "./src/assets/rice.avif";
import chicken from "./src/assets/chicken.avif";
import sandwich from "./src/assets/sandwich.avif";


const foodItems = [
  {
    id: 1,
    food_name: "Margherita Pizza",
    food_category: "Pizza",
    food_type: "Veg",
    food_quantity: "1 plate",
    food_image: pizza,
    price: 199,
  },
  {
    id: 2,
    food_name: "Pepperoni Pizza",
    food_category: "Pizza",
    food_type: "Non-Veg",
    food_quantity: "1 plate",
    food_image: pizza,
    price: 299,
  },
  {
    id: 3,
    food_name: "Veg Burger",
    food_category: "Burgers",
    food_type: "Veg",
    food_quantity: "1 piece",
    food_image: burger,
    price: 129,
  },
  {
    id: 4,
    food_name: "Chicken Burger",
    food_category: "Burgers",
    food_type: "Non-Veg",
    food_quantity: "1 piece",
    food_image: burger,
    price: 149,
  },
  {
    id: 5,
    food_name: "White Sauce Pasta",
    food_category: "Pasta",
    food_type: "Veg",
    food_quantity: "1 bowl",
    food_image: pasta,
    price: 199,
  },
  {
    id: 6,
    food_name: "Red Sauce Pasta",
    food_category: "Pasta",
    food_type: "Veg",
    food_quantity: "1 bowl",
    food_image: pasta,
    price: 179,
  },
  {
    id: 7,
    food_name: "Tomato Soup",
    food_category: "Soup",
    food_type: "Veg",
    food_quantity: "1 bowl",
    food_image: soup,
    price: 100,
  },
  {
    id: 8,
    food_name: "Chicken Soup",
    food_category: "Soup",
    food_type: "Non-Veg",
    food_quantity: "1 bowl",
    food_image: soup,
    price: 120,
  },
  {
    id: 9,
    food_name: "Masala Dosa",
    food_category: "Breakfast",
    food_type: "Veg",
    food_quantity: "2 pieces",
    food_image: dosa,
    price: 99,
  },
  {
    id: 10,
    food_name: "Paneer Butter Masala",
    food_category: "Main Course",
    food_type: "Veg",
    food_quantity: "1 bowl",
    food_image: paneer,
    price: 220,
  },
  {
    id: 11,
    food_name: "Chicken Biryani",
    food_category: "Main Course",
    food_type: "Non-Veg",
    food_quantity: "1 plate",
    food_image: biryani,
    price: 249,
  },
  {
    id: 12,
    food_name: "Veg Sandwich",
    food_category: "Breakfast",
    food_type: "Veg",
    food_quantity: "2 pieces",
    food_image: sandwich,
    price: 89,
  },
  {
    id: 13,
    food_name: "Pancakes",
    food_category: "Breakfast",
    food_type: "Veg",
    food_quantity: "3 pieces",
    food_image: pancakes,
    price: 150,
  },
  {
    id: 14,
    food_name: "French Fries",
    food_category: "Snacks",
    food_type: "Veg",
    food_quantity: "1 plate",
    food_image: fries,
    price: 90,
  },
  {
    id: 15,
    food_name: "Ice Cream",
    food_category: "Dessert",
    food_type: "Veg",
    food_quantity: "1 scoop",
    food_image: icecream,
    price: 80,
  },
  {
    id: 16,
    food_name: "Chocolate Cake",
    food_category: "Dessert",
    food_type: "Veg",
    food_quantity: "1 slice",
    food_image: cake,
    price: 120,
  },
  {
    id: 17,
    food_name: "Hakka Noodles",
    food_category: "Main Course",
    food_type: "Veg",
    food_quantity: "1 plate",
    food_image: noodles,
    price: 160,
  },
  {
    id: 18,
    food_name: "Chicken Noodles",
    food_category: "Main Course",
    food_type: "Non-Veg",
    food_quantity: "1 plate",
    food_image: noodles,
    price: 180,
  },
  {
    id: 19,
    food_name: "Fried Rice",
    food_category: "Main Course",
    food_type: "Veg",
    food_quantity: "1 plate",
    food_image: rice,
    price: 150,
  },
  {
    id: 20,
    food_name: "Chicken Fried Rice",
    food_category: "Main Course",
    food_type: "Non-Veg",
    food_quantity: "1 plate",
    food_image: rice,
    price: 190,
  },
  {
    id: 21,
    food_name: "Grilled Chicken",
    food_category: "Main Course",
    food_type: "Non-Veg",
    food_quantity: "1 plate",
    food_image: chicken,
    price: 270,
  },
  {
    id: 22,
    food_name: "Paneer Tikka",
    food_category: "Snacks",
    food_type: "Veg",
    food_quantity: "1 plate",
    food_image: paneer,
    price: 200,
  },
  {
    id: 23,
    food_name: "Veg Momos",
    food_category: "Snacks",
    food_type: "Veg",
    food_quantity: "6 pieces",
    food_image: noodles,
    price: 110,
  },
  {
    id: 24,
    food_name: "Chicken Momos",
    food_category: "Snacks",
    food_type: "Non-Veg",
    food_quantity: "6 pieces",
    food_image: chicken,
    price: 130,
  },
  {
    id: 25,
    food_name: "Cold Coffee",
    food_category: "Beverages",
    food_type: "Veg",
    food_quantity: "1 glass",
    food_image: icecream,
    price: 140,
  },
];

export default foodItems;